version: 2

models:
  - name: away_table
    description: >
      Table for teams performance away from home

  - name: home_table
    description: >
      Table for teams performance at home

  - name: matchday_wise_tally
    description: >
      Aggregated table of performance of teams on the basis of matchdays akin to time series data.

  - name: overall_table
    description: >
      Table for teams performance throughout season till date