football:
  target: dev
  outputs:
    dev:
      dataset: "{{ env_var('BQ_DATASET_NAME') }}"
      job_execution_timeout_seconds: 6000
      job_retries: 1
      keyfile: "{{ env_var('GOOGLE_SERVICE_ACC_KEY_FILEPATH') }}"
      location: "{{ env_var('LOCATION') }}"
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      threads: 4
      type: bigquery

