football:
  target: dev
  outputs:
    dev:
      dataset: capstone
      job_execution_timeout_seconds: 6000
      job_retries: 1
      keyfile: /home/src/capstone.json
      location: US
      method: service-account
      priority: interactive
      project: dtc-de-course-411615
      threads: 4
      type: bigquery

